### ISSUE TITLE
A typo in predict.py

### ISSUE THREAD

**Issue by Harikrishnan6336** [nandakishormpai2001/movie_review_predictor#1]
@nandakishormpai2001 There is a typo in predict.py at line 160.The word maxlength has been mispelled as maxlenght. Kindly assign me this issue.

**Comment by nandakishormpai** [comment]
sorry to say i didnt find so..can you share a screenshot or the part where it is wrong

**Comment by Harikrishnan6336** [comment]
@nandakishormpai2001  Oops the mistake is in train.py at line 160
