### ISSUE TITLE
Vocab.txt is generated twice

### ISSUE THREAD

**Issue by Harikrishnan6336** [nandakishormpai2001/movie_review_predictor#2]
@nandakishormpai2001  According to the source code vocab.txt is generated in train.py .
But again in predict.py the same vocab.txt is generated again leading to more time consumption.
Actually predict.py run successfully even if the lines from 69 to 95 in predict.py is avoided

**Comment by Harikrishnan6336** [comment]
@nandakishormpai2001  In fact there is no need for lines 20 to 95 in predict.py

**Comment by nandakishormpai** [comment]
you were right. but now i have decided to remove train.py as the saved model can predict. so now i have to load vocab in predict

**Comment by nandakishormpai** [comment]
thanks for your suggestion. i have just loaded vocab.txt instead of making it every time you predict
